language: bash

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cabal-install

# Check scrips for warnings/errors
before_install:
  - cabal update && cabal install ShellCheck
  - export PATH=$PATH:$HOME/.cabal/bin
  - shellcheck --version
script:
  - ./run.shellcheck

# Notification settings
notifications:
  slack: meteoswiss-apn:FFUYLitE3BsncqECl4RqlfHP
  email:
    on_success: never
    on_failure: always
