#!/bin/bash

#
# Script used to build clang/openmp with offload support on leconte
#

# git clone git@github.com:clementval/llvm-project.git
# cd llvm-project || exit 1
# git checkout mlir/openacc/draft
# mkdir build
# cd build || exit 1

# These modules are known to work
module load gnu/7.5.0
module load cuda/9.2

export INSTALL_PATH_CLANG=/home/4vn/versioning/llvm-project/install/leconte

# Build clang only
cmake -G "Unix Makefiles" ../llvm -DLLVM_ENABLE_PROJECTS="clang" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$(INSTALL_PATH_CLANG)" \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_CXX_COMPILER=g++

make -j 64
make -j 32 install
rm -rf ./*

# Rebuild clang and openmp libraries with previously built clang
cmake -G "Unix Makefiles" ../llvm \
  -DLLVM_ENABLE_PROJECTS="clang;openmp" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/home/4vn/install/leconte/clang-build-RELEASE_master \
  -DCMAKE_C_COMPILER="$(INSTALL_PATH_CLANG)"/bin/clang \
  -DCMAKE_C_FLAGS="--gcc-toolchain=/auto/software/gcc/ppc64le/gcc-7.5.0" \
  -DCMAKE_CXX_COMPILER="$(INSTALL_PATH_CLANG)"/bin/clang++ \
  -DCMAKE_CXX_FLAGS="--gcc-toolchain=/auto/software/gcc/ppc64le/gcc-7.5.0" \
  -DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_70 \
  -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES=70

make -j 64
make -j 32 install

# -fopenmp-targets=ppc64le-unknown-linux-gnu
# -fopenmp-targets=nvptx64-nvidia-cuda --cuda-gpu-arch=sm_70